server:
  port: 9012
spring:
  application:
    name: discovery-service
  cloud:
    config:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9012/eureka/
    register-with-eureka: false
    fetch-registry: false