server:
  port: 8889
spring:
  application:
    name: discovery-server
  cloud:
    config:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/
    register-with-eureka: false
    fetch-registry: false